image: alpine/edge
packages:
  - pandoc
  - curl
  - jq
secrets:
  - e7beae88-cb59-401c-b01b-94842c6f8556
environment:
  REPO_ID: 111799
  README: README.html
tasks:
  - convert-readme: |
      pandoc -o README.html clj-learn-api/README.org
  - update-readme: |
      set +x  # Avoid echoing the token
      jq -sR '{
          "query": "mutation UpdateRepo($id: Int!, $readme: String!) {
                       updateRepository(id: $id, input: { readme: $readme }) { id }
                   }",
          "variables": {
            "id": '$REPO_ID',
            "readme": .
          } }' < $README \
        | curl --oauth2-bearer "$(cat ~/.api-token)" \
          -H "Content-Type: application/json" \
          -d@- https://git.sr.ht/query &&
      echo "README set"
